### ISSUE TITLE
Is there any way for e-commerce search using elasticsearch?

### ISSUE THREAD

**Issue by sagarjainubuy** [spinscale/elasticsearch-ingest-langdetect#12]
Is there any way for e-commerce search using elasticsearch?

**Comment by spinscale** [comment]
This is a issue tracker for the langdetect plugin. Your question has nothing to do with the plugin.

I think your best bet would be to ask your question in the Elastic Stack Discuss forum, available at https://discuss.elastic.co/

**Comment by sagarjainubuy** [comment]
I have already posted on https://discuss.elastic.co/
I want to know your suggestions
