### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by yuuiki** [spinscale/elasticsearch-ingest-langdetect#13]
sorry to disturb, I try to install this plugin but fail, pls see this image. 
![image](https://user-images.githubusercontent.com/29880212/90737341-aa023d00-e300-11ea-933c-13c8b6d524ad.png)
and I dont understand when and which directory should I run this coommad 'gradle clean check', and where can I find this file
"build/distributions"

sorry I'm a new starter to es, I will be appreciative if I can get your replyment！

**Comment by spinscale** [comment]
You do not need to run any gradle command to install the plugin. The README states the command to run for each plugin version... that's all that is needed. See https://github.com/spinscale/elasticsearch-ingest-langdetect
