### ISSUE TITLE
Elastic 7.16.2

### ISSUE THREAD

**Issue by RolfDeVries** [spinscale/elasticsearch-ingest-langdetect#15]
Hi, when can you provide this plugin for elastic 7.16.2 (released yesterday)

**Comment by spinscale** [comment]
I just did a release. Keep in mind that this is an open source project done in free time and thus comes with no fixed releases or time lines, so a little more kindness instead of such a single sentence demand is much appreciated.

**Comment by RolfDeVries** [comment]
Excuses for the short request, no intentions to be unkind, sorry for that. We appriociate the plugin very much! 
It works perfectly! Would you be so kind to create a 8.1.0 version as well :-) Very many thanks!

**Comment by spinscale** [comment]
So there is an issue with plugin testing framework released alongside 8.1.0, thus the delay. I have a local version running against testcontainers and might just ship that one... just bear a little longer.

**Comment by spinscale** [comment]
please test the 8.1 release and see if it works, with those changes...

**Comment by RolfDeVries** [comment]
Looks very good for NL and EN, we dont use other language, thank you very much!
