### ISSUE TITLE
Is there a way to include multiple lang detect processors while indexing?

### ISSUE THREAD

**Issue by maninov88** [spinscale/elasticsearch-ingest-langdetect#16]
After indexing I would like to know the language code of multiple fields. Example, created multiple pipelines which does lang detection on different fields and expecting to see language code of each fields after indexing.
Looking for something like below

http://index1/_doc/doc1?pipeline=langdetect-pipeline1,langdetect-pipeline2,... {
some content
}

**Comment by maninov88** [comment]
Also, would like to know if the plugin is applicable on _reindex api?

**Comment by spinscale** [comment]
This is not a plugin question, but how pipelines work. You can use the processor more than once in a pipeline, so its not a problem to look up several fields. You can also reference another pipeline within a pipeline, see  https://www.elastic.co/guide/en/elasticsearch/reference/8.4/pipeline-processor.html

An if you can specify a processor in a pipeline it can always be used in reindex.
