### ISSUE TITLE
Configuration for connecting spring data elasticsearch with elasticsearch 8.5 with security

### ISSUE THREAD

**Issue by touseef306** [spinscale/elasticsearch-ingest-langdetect#17]
Hi ,
I watched your video on youtube, https://www.youtube.com/watch?v=84t_jC3dr3E. Can you please guide how to connect to elasticsearch 8.5 with spring data elasticsearch with security enabled

**Comment by spinscale** [comment]
Please use the official Elastic discussion forum at https://discuss.elastic.co/ for these kind of questions.
