### ISSUE TITLE
Plugin not loading under Windows

### ISSUE THREAD

**Issue by luc** [spinscale/elasticsearch-ingest-langdetect#3]
The tmp plugin file is not loading under Windows due to an java.net.URISyntaxException [here](https://github.com/spinscale/elasticsearch-ingest-langdetect/blob/master/src/main/java/com/cybozu/labs/langdetect/SecureDetectorFactory.java#L60).

A relative path on Windows filesystem ..\My Documents\test should be encoded using relative reference ../My%20Documents/test. You need to convert the backslash to slash manually for the relative path...

**Comment by netstyler** [comment]
Getting the same error here on windows with the version 6.2.4

**Comment by spinscale** [comment]
closed by 0221a4b6bc1b3c07b894b9d7cb80682f7702f05f
