### ISSUE TITLE
How to handle no features in non-empty text?

### ISSUE THREAD

**Issue by vegarsti** [spinscale/elasticsearch-ingest-langdetect#8]
Hi, thanks a lot for making this!
I'm using this at work where we're ingesting a lot of unstructured text documents, and we want to infer the language of the document. Some (a few) of these documents only contain numbers. In this case, the plugin throws this exception `com.cybozu.labs.langdetect.LangDetectException: no features in text`. What I want in this case is to just ignore the language field, as is done when the content is empty. Is there any way this can be done now? If not, I'll gladly try to help out with a PR, if that's possible!

**Comment by spinscale** [comment]
have you tried the `on_failure` directive as mentioned in https://www.elastic.co/guide/en/elasticsearch/reference/7.5/handling-failure-in-pipelines.html ? That should work. If not please provide a reproducible example here.

Thanks!

**Comment by vegarsti** [comment]
Oh, that's perfect, that link was exactly what I needed! In fact, I wanted `"ignore_failure": true`, instead of `on_failure`. Thank you!! And thanks for replying so quickly!
